# Generated by Django 5.1.7 on 2025-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price_per_kwh',
            field=models.IntegerField(help_text='Enter price in pence (e.g., 15 for £0.15)'),
        ),
    ]
